if spawn_room.sprite_index==spr_bg_indignados1_bg {instance_create(x,y,obj_map_indignados1_fg);}
else if spawn_room.sprite_index==spr_bg_indignados2_bg {instance_create(x,y,obj_map_indignados2_fg);}
else if spawn_room.sprite_index==spr_bg_indignados3_bg {instance_create(x,y,choose(obj_map_notav1_fg,obj_map_notav2_fg,obj_map_notav3_fg,obj_map_notav4_fg,obj_map_indignados3_fg,obj_map_keratea3_fg,obj_map_keratea4_fg,obj_map_occupy_fg,obj_map_extra1_fg));}
else if spawn_room.sprite_index==spr_bg_indignados4_bg {instance_create(x,y,choose(obj_map_notav1_fg,obj_map_notav2_fg,obj_map_notav3_fg,obj_map_notav4_fg,obj_map_indignados3_fg,obj_map_keratea3_fg,obj_map_keratea4_fg,obj_map_occupy_fg,obj_map_extra1_fg));}
else if spawn_room.sprite_index==spr_bg_notav1_bg {instance_create(x,y,choose(obj_map_notav1_fg,obj_map_notav2_fg,obj_map_notav3_fg,obj_map_notav4_fg,obj_map_indignados3_fg,obj_map_keratea3_fg,obj_map_keratea4_fg,obj_map_occupy_fg,obj_map_extra1_fg));}
else if spawn_room.sprite_index==spr_bg_notav2_bg {instance_create(x,y,choose(obj_map_notav1_fg,obj_map_notav2_fg,obj_map_notav3_fg,obj_map_notav4_fg,obj_map_indignados3_fg,obj_map_keratea3_fg,obj_map_keratea4_fg,obj_map_occupy_fg,obj_map_extra1_fg));}
else if spawn_room.sprite_index==spr_bg_notav3_bg {instance_create(x,y,choose(obj_map_notav1_fg,obj_map_notav2_fg,obj_map_notav3_fg,obj_map_notav4_fg,obj_map_indignados3_fg,obj_map_keratea3_fg,obj_map_keratea4_fg,obj_map_occupy_fg,obj_map_extra1_fg));}
else if spawn_room.sprite_index==spr_bg_notav4_bg {instance_create(x,y,choose(obj_map_notav1_fg,obj_map_notav2_fg,obj_map_notav3_fg,obj_map_notav4_fg,obj_map_indignados3_fg,obj_map_keratea3_fg,obj_map_keratea4_fg,obj_map_occupy_fg,obj_map_extra1_fg));}
else if spawn_room.sprite_index==spr_bg_keratea1_bg {instance_create(x,y,obj_map_keratea1_fg);}
else if spawn_room.sprite_index==spr_bg_keratea2_bg {instance_create(x,y,obj_map_keratea2_fg);}
else if spawn_room.sprite_index==spr_bg_keratea3_bg {instance_create(x,y,choose(obj_map_notav1_fg,obj_map_notav2_fg,obj_map_notav3_fg,obj_map_notav4_fg,obj_map_indignados3_fg,obj_map_keratea3_fg,obj_map_keratea4_fg,obj_map_occupy_fg,obj_map_extra1_fg));}
else if spawn_room.sprite_index==spr_bg_keratea4_bg {instance_create(x,y,choose(obj_map_notav1_fg,obj_map_notav2_fg,obj_map_notav3_fg,obj_map_notav4_fg,obj_map_indignados3_fg,obj_map_keratea3_fg,obj_map_keratea4_fg,obj_map_occupy_fg,obj_map_extra1_fg));}
else if spawn_room.sprite_index==spr_bg_tahrir1_bg {instance_create(x,y,obj_map_tahrir1_fg);}
else if spawn_room.sprite_index==spr_bg_tahrir2_bg {instance_create(x,y,obj_map_tahrir2_fg);}
else if spawn_room.sprite_index==spr_bg_tahrir3_bg {instance_create(x,y,obj_map_tahrir3_fg);}
else if spawn_room.sprite_index==spr_bg_tahrir4_bg {instance_create(x,y,obj_map_tahrir4_fg);}
else if spawn_room.sprite_index==spr_bg_tahrir5_bg {instance_create(x,y,obj_map_tahrir5_fg);}
else if spawn_room.sprite_index==spr_bg_occupy_bg {instance_create(x,y,choose(obj_map_notav1_fg,obj_map_notav2_fg,obj_map_notav3_fg,obj_map_notav4_fg,obj_map_indignados3_fg,obj_map_keratea3_fg,obj_map_keratea4_fg,obj_map_occupy_fg,obj_map_extra1_fg));}
else if spawn_room.sprite_index==spr_bg_ukraine_bg {instance_create(x,y,obj_map_ukraine_fg);}
else if spawn_room.sprite_index==spr_bg_notav_extra1_bg {instance_create(x,y,choose(obj_map_notav1_fg,obj_map_notav2_fg,obj_map_notav3_fg,obj_map_notav4_fg,obj_map_indignados3_fg,obj_map_keratea3_fg,obj_map_keratea4_fg,obj_map_occupy_fg,obj_map_extra1_fg));}
else if spawn_room.sprite_index==spr_bg_notav_extra2_bg {instance_create(x,y,choose(obj_map_notav1_fg,obj_map_notav2_fg,obj_map_notav3_fg,obj_map_notav4_fg,obj_map_indignados3_fg,obj_map_keratea3_fg,obj_map_keratea4_fg,obj_map_occupy_fg,obj_map_extra1_fg,obj_map_extra2_fg));}
else if spawn_room.sprite_index==spr_bg_taksim_bg {instance_create(x,y,obj_map_taksim_fg);}
else if spawn_room.sprite_index==spr_bg_syntagma_day {instance_create(x,y,choose(obj_map_notav1_fg,obj_map_notav2_fg,obj_map_notav3_fg,obj_map_notav4_fg,obj_map_indignados3_fg,obj_map_keratea3_fg,obj_map_keratea4_fg,obj_map_occupy_fg,obj_map_extra1_fg));}
else if spawn_room.sprite_index==spr_bg_library_bg {instance_create(x,y,obj_map_library_fg);}
else if spawn_room.sprite_index==spr_bg_korea_bg {instance_create(x,y,choose(obj_map_notav1_fg,obj_map_notav2_fg,obj_map_notav3_fg,obj_map_notav4_fg,obj_map_indignados3_fg,obj_map_keratea3_fg,obj_map_keratea4_fg,obj_map_occupy_fg,obj_map_extra1_fg));}
else if spawn_room.sprite_index==spr_bg_indignados1_bg_n {instance_create(x,y,obj_map_indignados1_fg);}
else if spawn_room.sprite_index==spr_bg_indignados2_bg_n {instance_create(x,y,obj_map_indignados2_fg);}
else if spawn_room.sprite_index==spr_bg_indignados3_bg_n {instance_create(x,y,choose(obj_map_notav1_fg,obj_map_notav2_fg,obj_map_notav3_fg,obj_map_notav4_fg,obj_map_indignados3_fg,obj_map_keratea3_fg,obj_map_keratea4_fg,obj_map_occupy_fg,obj_map_extra1_fg));}
else if spawn_room.sprite_index==spr_bg_indignados4_bg_n {instance_create(x,y,choose(obj_map_notav1_fg,obj_map_notav2_fg,obj_map_notav3_fg,obj_map_notav4_fg,obj_map_indignados3_fg,obj_map_keratea3_fg,obj_map_keratea4_fg,obj_map_occupy_fg,obj_map_extra1_fg));}
else if spawn_room.sprite_index==spr_bg_notav1_bg_n {instance_create(x,y,choose(obj_map_notav1_fg,obj_map_notav2_fg,obj_map_notav3_fg,obj_map_notav4_fg,obj_map_indignados3_fg,obj_map_keratea3_fg,obj_map_keratea4_fg,obj_map_occupy_fg,obj_map_extra1_fg));}
else if spawn_room.sprite_index==spr_bg_notav2_bg_n {instance_create(x,y,choose(obj_map_notav1_fg,obj_map_notav2_fg,obj_map_notav3_fg,obj_map_notav4_fg,obj_map_indignados3_fg,obj_map_keratea3_fg,obj_map_keratea4_fg,obj_map_occupy_fg,obj_map_extra1_fg));}
else if spawn_room.sprite_index==spr_bg_notav3_bg_n {instance_create(x,y,choose(obj_map_notav1_fg,obj_map_notav2_fg,obj_map_notav3_fg,obj_map_notav4_fg,obj_map_indignados3_fg,obj_map_keratea3_fg,obj_map_keratea4_fg,obj_map_occupy_fg,obj_map_extra1_fg));}
else if spawn_room.sprite_index==spr_bg_notav4_bg_n {instance_create(x,y,choose(obj_map_notav1_fg,obj_map_notav2_fg,obj_map_notav3_fg,obj_map_notav4_fg,obj_map_indignados3_fg,obj_map_keratea3_fg,obj_map_keratea4_fg,obj_map_occupy_fg,obj_map_extra1_fg));}
else if spawn_room.sprite_index==spr_bg_keratea1_bg_n {instance_create(x,y,obj_map_keratea1_fg);}
else if spawn_room.sprite_index==spr_bg_keratea2_bg_n {instance_create(x,y,obj_map_keratea2_fg);}
else if spawn_room.sprite_index==spr_bg_keratea3_bg_n {instance_create(x,y,choose(obj_map_notav1_fg,obj_map_notav2_fg,obj_map_notav3_fg,obj_map_notav4_fg,obj_map_indignados3_fg,obj_map_keratea3_fg,obj_map_keratea4_fg,obj_map_occupy_fg,obj_map_extra1_fg));}
else if spawn_room.sprite_index==spr_bg_keratea4_bg_n {instance_create(x,y,choose(obj_map_notav1_fg,obj_map_notav2_fg,obj_map_notav3_fg,obj_map_notav4_fg,obj_map_indignados3_fg,obj_map_keratea3_fg,obj_map_keratea4_fg,obj_map_occupy_fg,obj_map_extra1_fg));}
else if spawn_room.sprite_index==spr_bg_tahrir1_bg_n {instance_create(x,y,obj_map_tahrir1_fg);}
else if spawn_room.sprite_index==spr_bg_tahrir2_bg_n {instance_create(x,y,obj_map_tahrir2_fg);}
else if spawn_room.sprite_index==spr_bg_tahrir3_bg_n {instance_create(x,y,obj_map_tahrir3_fg);}
else if spawn_room.sprite_index==spr_bg_tahrir4_bg_n {instance_create(x,y,obj_map_tahrir4_fg);}
else if spawn_room.sprite_index==spr_bg_tahrir5_bg_n {instance_create(x,y,obj_map_tahrir5_fg);}
else if spawn_room.sprite_index==spr_bg_occupy_bg_n {instance_create(x,y,choose(obj_map_notav1_fg,obj_map_notav2_fg,obj_map_notav3_fg,obj_map_notav4_fg,obj_map_indignados3_fg,obj_map_keratea3_fg,obj_map_keratea4_fg,obj_map_occupy_fg,obj_map_extra1_fg));}
else if spawn_room.sprite_index==spr_bg_ukraine_bg_n {instance_create(x,y,obj_map_ukraine_fg);}
else if spawn_room.sprite_index==spr_bg_notav_extra1_bg_n {instance_create(x,y,choose(obj_map_notav1_fg,obj_map_notav2_fg,obj_map_notav3_fg,obj_map_notav4_fg,obj_map_indignados3_fg,obj_map_keratea3_fg,obj_map_keratea4_fg,obj_map_occupy_fg,obj_map_extra1_fg));}
else if spawn_room.sprite_index==spr_bg_notav_extra2_bg_n {instance_create(x,y,choose(obj_map_notav1_fg,obj_map_notav2_fg,obj_map_notav3_fg,obj_map_notav4_fg,obj_map_indignados3_fg,obj_map_keratea3_fg,obj_map_keratea4_fg,obj_map_occupy_fg,obj_map_extra1_fg,obj_map_extra2_fg));}
else if spawn_room.sprite_index==spr_bg_taksim_bg_n {instance_create(x,y,obj_map_taksim_fg);}
else if spawn_room.sprite_index==spr_bg_syntagma_night {instance_create(x,y,choose(obj_map_notav1_fg,obj_map_notav2_fg,obj_map_notav3_fg,obj_map_notav4_fg,obj_map_indignados3_fg,obj_map_keratea3_fg,obj_map_keratea4_fg,obj_map_occupy_fg,obj_map_extra1_fg));}
else if spawn_room.sprite_index==spr_bg_library_bg_n {instance_create(x,y,obj_map_library_fg);}
else if spawn_room.sprite_index==spr_bg_korea_bg_n {instance_create(x,y,choose(obj_map_notav1_fg,obj_map_notav2_fg,obj_map_notav3_fg,obj_map_notav4_fg,obj_map_indignados3_fg,obj_map_keratea3_fg,obj_map_keratea4_fg,obj_map_occupy_fg,obj_map_extra1_fg,obj_map_korea_fg));}
else {instance_create(x,y,choose(obj_map_notav1_fg,obj_map_notav2_fg,obj_map_notav3_fg,obj_map_notav4_fg,obj_map_indignados3_fg,obj_map_keratea3_fg,obj_map_keratea4_fg,obj_map_occupy_fg,obj_map_extra1_fg));}