nation="";
character=choose(0,1,2,0,1,2,0,1,2,3);//which voice character to choose
wait_time=room_speed*random_range(5,15);//time to reset
tired_time=room_speed*150;//play time before they get tired
switch_status="default"
voice=snd_null;
voice_pitch=1;
voice_volume=1;

alarm[0]=1;

//choose nation
if room=rm_indignados1
|| room=rm_indignados2
|| room=rm_indignados3
|| room=rm_indignados4
{nation="Spain";}
if room=rm_notav1
|| room=rm_notav2
|| room=rm_notav3
|| room=rm_notav4
|| room=rm_notav_extra2
{nation="Italy";}
if room=rm_keratea1
|| room=rm_keratea2
|| room=rm_keratea3
|| room=rm_keratea4
|| room=rm_syntagma
{nation="Greece";}
if room=rm_tahrir1
|| room=rm_tahrir2
|| room=rm_tahrir3
|| room=rm_tahrir4
|| room=rm_tahrir5
|| room=rm_library
{nation="Egypt";}
if room=rm_korea
{nation="Korea";}
if room=rm_taksim
{nation="Turkey";}
if room=rm_occupy
|| room=rm_notav_extra1
{nation="USA";}
if room=rm_indignados_complete
{nation=choose("Spain","USA");}
if room=rm_notav_complete
{nation="Italy";}
if room=rm_keratea_complete
{nation=choose("Greece","Turkey");}
if room=rm_tahrir_complete
{nation=choose("Egypt","Korea");}
if room=rm_random
{nation=choose("Spain","Italy","Greece","Egypt","Korea","Turkey","USA");}