depth=global.depth_menu;
global.ai=false;

instance_create(x,y,obj_menu_transition);

b_notav1r=instance_create(x,y,obj_menu_button);
b_notav1p=instance_create(x,y,obj_menu_button);
b_notav2r=instance_create(x,y,obj_menu_button);
b_notav2p=instance_create(x,y,obj_menu_button);
b_notav3r=instance_create(x,y,obj_menu_button);
b_notav3p=instance_create(x,y,obj_menu_button);
b_notav4r=instance_create(x,y,obj_menu_button);
b_notav4p=instance_create(x,y,obj_menu_button);
b_notav_extra1r=instance_create(x,y,obj_menu_button);
b_notav_extra1p=instance_create(x,y,obj_menu_button);
b_notav_extra2r=instance_create(x,y,obj_menu_button);
b_notav_extra2p=instance_create(x,y,obj_menu_button);
b_back=instance_create(x,y,obj_menu_button);

ini_open("save.ini");
//NOTAV1Dr
b_notav1r.active=ini_read_real("MAPS","notav1r",0);
b_notav1r.sprite=spr_menu_notav_story_1R;
b_notav1r.target_night=0;
b_notav1r.target_room=rm_notav1;
//NOTAV1Np
b_notav1p.active=ini_read_real("MAPS","notav1p",0);
b_notav1p.sprite=spr_menu_notav_story_1P;
b_notav1p.target_night=1;
b_notav1p.target_room=rm_notav1;
//NOTAV2Dr
b_notav2r.active=ini_read_real("MAPS","notav2r",0);
b_notav2r.sprite=spr_menu_notav_story_2R;
b_notav2r.target_night=0;
b_notav2r.target_room=rm_notav2;
//NOTAV2Np
b_notav2p.active=ini_read_real("MAPS","notav2p",0);
b_notav2p.sprite=spr_menu_notav_story_2P;
b_notav2p.target_night=1;
b_notav2p.target_room=rm_notav2;
//NOTAV3Dr
b_notav3r.active=ini_read_real("MAPS","notav3r",0);
b_notav3r.sprite=spr_menu_notav_story_3R;
b_notav3r.target_night=0;
b_notav3r.target_room=rm_notav3;
//NOTAV3Np
b_notav3p.active=ini_read_real("MAPS","notav3p",0);
b_notav3p.sprite=spr_menu_notav_story_3P;
b_notav3p.target_night=1;
b_notav3p.target_room=rm_notav3;
//NOTAV4Dr
b_notav4r.active=ini_read_real("MAPS","notav4r",0);
b_notav4r.sprite=spr_menu_notav_story_4R;
b_notav4r.target_night=0;
b_notav4r.target_room=rm_notav4;
//NOTAV4Np
b_notav4p.active=ini_read_real("MAPS","notav4p",0);
b_notav4p.sprite=spr_menu_notav_story_4P;
b_notav4p.target_night=1;
b_notav4p.target_room=rm_notav4;
//EXTRA1Dr
b_notav_extra1r.active=ini_read_real("MAPS","extra1r",0);
b_notav_extra1r.sprite=spr_menu_notav_versus_nomuos;
b_notav_extra1r.target_night=0
b_notav_extra1r.target_room=rm_notav_extra1;
//EXTRA1Np
b_notav_extra1p.active=ini_read_real("MAPS","extra1p",0);
b_notav_extra1p.sprite=spr_menu_notav_versus_nomuos_n;
b_notav_extra1p.target_night=1
b_notav_extra1p.target_room=rm_notav_extra1;
//EXTRA2Dr
b_notav_extra2r.active=ini_read_real("MAPS","extra2r",0);
b_notav_extra2r.sprite=spr_menu_notav_versus_rome;
b_notav_extra2r.target_night=0
b_notav_extra2r.target_room=rm_notav_extra2;
//EXTRA2Np
b_notav_extra2p.active=ini_read_real("MAPS","extra2p",0);
b_notav_extra2p.sprite=spr_menu_notav_versus_rome_n;
b_notav_extra2p.target_night=1
b_notav_extra2p.target_room=rm_notav_extra2;
ini_close();

//BACK
b_back.active=1;
b_back.sprite=spr_menu_notav_story_back;
b_back.target_room=rm_menu;
