nextroom=rm_tahrir5;
music=snd_music_tahrir5;
sound_fx=snd_sfx_tahrir5;
global.night=true;
audio_stop_all();
audio_play_sound(sound_fx,100,false);
audio_play_sound(music,100,false);
audio_sound_gain(sound_fx,global.audio_cinematics,0);
audio_sound_gain(music,global.audio_music,0);
